In [1]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

In [2]:
ground_value = pd.read_csv('2022 표준지 공시지가.csv', sep=',', header=0)
ground_value.head()

,일련번호,시군구,읍면동리,지번구분,본번지,부번지,시도명,시군구명,소재지,지목,...,용도지역2,이용상황,주위환경,지세명,형상명,도로교통,공시지가,지리적위치1,지리적위치2,방위
0,1,11110,10100,1,0003,52,서울특별시,종로구,청운동 3-52,공원,...,NaN,공원등,시가지주변 야산지대,급경사지,부정형,세로(불),493500,경기상고,북측 인근,NaN
1,2,11110,10100,1,0004,2,서울특별시,종로구,청운동 4-2,임야,...,NaN,자연림,시가지주변 야산지대,완경사지,부정형,맹지,730500,경가상고,북서측 근거리,남향
2,3,11110,10100,1,0004,15,서울특별시,종로구,청운동 4-15,대,...,NaN,단독주택,기존 주택지대,완경사지,사다리형,세로(가),4250000,경기상고,북서측 인근,북동향
3,4,11110,10100,1,0008,9,서울특별시,종로구,청운동 8-9,대,...,NaN,연립주택,일반 주택지대,급경사지,부정형,세로(가),3930000,청운중학교,서측인근,남향
4,5,11110,10100,1,0008,15,서울특별시,종로구,청운동 8-15,대,...,NaN,연립주택,기존 주택지대,급경사지,사다리형,세로(가),3855000,경기상고,서측인근,남서향

In [3]:
ground2 = ground_value.copy()

In [4]:
ground_data = pd.read_csv('ground.csv', sep=',', header=0, encoding = 'cp949')
ground_data.head()

,시도명,시군구명,지목,면적,용도지역1,용도지역2,이용상황,주위환경,지세명,형상명,도로교통,방위,지리적위치1_2,지리적위치2_2
0,7,0,0,1021.5,0,0,0,0,0,0,0,0,0,0
1,7,0,1,723.3,1,0,1,0,1,0,1,1,0,0
2,7,0,2,416.2,1,0,2,1,1,1,2,7,0,0
3,7,0,2,811.3,1,0,3,2,0,0,2,1,0,0
4,7,0,2,442.3,1,0,3,1,0,1,2,4,0,0

In [7]:
ground3 = pd.concat([ground_data, ground2['공시지가']], axis = 1)

In [8]:
ground3

,시도명,시군구명,지목,면적,용도지역1,용도지역2,이용상황,주위환경,지세명,형상명,도로교통,방위,지리적위치1_2,지리적위치2_2,공시지가
0,7,0,0,1021.5,0,0,0,0,0,0,0,0,0,0,493500
1,7,0,1,723.3,1,0,1,0,1,0,1,1,0,0,730500
2,7,0,2,416.2,1,0,2,1,1,1,2,7,0,0,4250000
3,7,0,2,811.3,1,0,3,2,0,0,2,1,0,0,3930000
4,7,0,2,442.3,1,0,3,1,0,1,2,4,0,0,3855000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540045,12,227,7,8473.0,21,0,27,66,2,1,1,0,0,0,18500
540046,12,227,7,12365.0,21,0,18,65,2,1,9,0,0,0,61000
540047,12,227,14,2912.0,21,0,27,66,1,0,2,0,0,0,49500
540048,12,227,14,1537.0,21,0,27,66,1,0,7,0,0,0,89000
540049,12,227,23,1888.0,19,0,48,88,1,0,1,4,0,0,3850

In [9]:
target = ground3['공시지가']

In [10]:
ground_data = ground3[ground3.columns.difference(['공시지가','지리적위치1_2','지리적위치2_2'])]

In [11]:
ground_standardized = (ground_data - ground_data.mean()) / ground_data.std()

In [12]:
ground_data_standardized = pd.concat([target, ground_standardized], axis = 1)

In [13]:
ground_data_standardized

,공시지가,도로교통,면적,방위,시군구명,시도명,용도지역1,용도지역2,이용상황,주위환경,지목,지세명,형상명
0,493500,-0.984407,-0.138421,-0.638356,-1.971007,0.651107,-1.408877,-0.08546,-1.196356,-1.646720,-1.131306,-2.541281,-0.891892
1,730500,-0.663076,-0.154096,-0.210204,-1.971007,0.651107,-1.292501,-0.08546,-1.107603,-1.646720,-0.949966,-0.918271,-0.891892
2,4250000,-0.341744,-0.170238,2.358706,-1.971007,0.651107,-1.292501,-0.08546,-1.018850,-1.609504,-0.768626,-0.918271,-0.033347
3,3930000,-0.341744,-0.149470,-0.210204,-1.971007,0.651107,-1.292501,-0.08546,-0.930097,-1.572287,-0.768626,-2.541281,-0.891892
4,3855000,-0.341744,-0.168866,1.074251,-1.971007,0.651107,-1.292501,-0.08546,-0.930097,-1.609504,-0.768626,-2.541281,-0.033347
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540045,18500,-0.663076,0.253262,-0.638356,1.513764,1.944610,1.035025,-0.08546,1.199972,0.809583,0.138072,0.704739,-0.033347
540046,61000,1.907576,0.457842,-0.638356,1.513764,1.944610,1.035025,-0.08546,0.401196,0.772367,0.138072,0.704739,-0.033347
540047,49500,-0.341744,-0.039048,-0.638356,1.513764,1.944610,1.035025,-0.08546,1.199972,0.809583,1.407450,-0.918271,-0.891892
540048,89000,1.264913,-0.111324,-0.638356,1.513764,1.944610,1.035025,-0.08546,1.199972,0.809583,1.407450,-0.918271,-0.891892
540049,3850,-0.663076,-0.092874,1.074251,1.513764,1.944610,0.802272,-0.08546,3.063782,1.628351,3.039507,-0.918271,-0.891892

In [14]:
from statsmodels.formula.api import ols
my_formula = '공시지가 ~ 시도명 + 시군구명 + 지목 + 면적 + 용도지역1 + 용도지역2 + 이용상황 + 주위환경 + 지세명 + 형상명 + 도로교통 + 방위'
lm = ols(my_formula, data=ground_data_standardized).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   공시지가   R-squared:                       0.240
Model:                            OLS   Adj. R-squared:                  0.240
Method:                 Least Squares   F-statistic:                 1.424e+04
Date:                Fri, 20 Jan 2023   Prob (F-statistic):               0.00
Time:                        18:16:36   Log-Likelihood:            -8.6667e+06
No. Observations:              540050   AIC:                         1.733e+07
Df Residuals:                  540037   BIC:                         1.733e+07
Df Model:                          12
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   7.922e+05   3069.667    258.077      0.000    7.86e+05    7.98e+05
시도명        -2.926e+05   3844.224    -76.116      0.000      -3e+05   -2.85e+05
시군구명        -8.58e+05   4124.674   -208.021      0.000   -8.66e+05    -8.5e+05
지목         -2.861e+05   6353.776    -45.022      0.000   -2.99e+05   -2.74e+05
면적         -4690.5307   3176.565     -1.477      0.140   -1.09e+04    1535.436
용도지역1      -1.057e+05   3949.704    -26.770      0.000   -1.13e+05    -9.8e+04
용도지역2       2.668e+04   3113.015      8.569      0.000    2.06e+04    3.28e+04
이용상황       -5.019e+04   6647.457     -7.551      0.000   -6.32e+04   -3.72e+04
주위환경       -3.274e+05   3868.020    -84.639      0.000   -3.35e+05    -3.2e+05
지세명         9.908e+04   3610.967     27.437      0.000     9.2e+04    1.06e+05
형상명         2.034e+05   3533.968     57.542      0.000    1.96e+05     2.1e+05
도로교통        2.094e+05   3483.641     60.111      0.000    2.03e+05    2.16e+05
방위         -2.971e+05   3899.279    -76.183      0.000   -3.05e+05   -2.89e+05
==============================================================================
Omnibus:                  1158145.305   Durbin-Watson:                   0.468
Prob(Omnibus):                  0.000   Jarque-Bera (JB):      14204001095.073
Skew:                          18.726   Prob(JB):                         0.00
Kurtosis:                     796.617   Cond. No.                         5.15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [25]:
ground_data = pd.concat([ground3['시도명'],ground3['시군구명'], ground3['지목'], ground3['면적'],
                        ground3['용도지역2'], ground3['이용상황'],ground3['주위환경'],
                        ground3['지세명'],ground3['형상명'], ground3['도로교통']
                        ,ground3['방위']], axis =1)

In [26]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Lasso

In [27]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(ground_data, target, random_state=42)

In [28]:
poly = PolynomialFeatures(include_bias=False)

poly.fit(train_input)
train_poly = poly.transform(train_input)
test_poly = poly.transform(test_input)

# 규제전 표준화

In [29]:
ss = StandardScaler() # 표준화 작업을 함수로서 지원
ss.fit(train_poly)

train_scaled = ss.transform(train_poly)
test_scaled = ss.transform(test_poly)

In [30]:
lasso = Lasso(0.001)
lasso.fit(train_scaled, train_target)
print(f'training_score : {lasso.score(train_scaled, train_target)}')
print(f'test_score : {lasso.score(test_scaled, test_target)}')

training_score : 0.4073018339465979
test_score : 0.3730265842272551

# 라쏘 실행

In [ ]:
lasso = Lasso(0.01)
lasso.fit(train_scaled, train_target)
print(f'training_score : {lasso.score(train_scaled, train_target)}')
print(f'test_score : {lasso.score(test_scaled, test_target)}')

In [ ]:
lasso = Lasso(0.1)
lasso.fit(train_scaled, train_target)
print(f'training_score : {lasso.score(train_scaled, train_target)}')
print(f'test_score : {lasso.score(test_scaled, test_target)}')

In [ ]:
lasso = Lasso(1)
lasso.fit(train_scaled, train_target)
print(f'training_score : {lasso.score(train_scaled, train_target)}')
print(f'test_score : {lasso.score(test_scaled, test_target)}')

In [ ]:
lasso = Lasso(10)
lasso.fit(train_scaled, train_target)
print(f'training_score : {lasso.score(train_scaled, train_target)}')
print(f'test_score : {lasso.score(test_scaled, test_target)}')

In [ ]:
lasso = Lasso(100)
lasso.fit(train_scaled, train_target)
print(f'training_score : {lasso.score(train_scaled, train_target)}')
print(f'test_score : {lasso.score(test_scaled, test_target)}')

In [ ]:
lasso = Lasso(1000)
lasso.fit(train_scaled, train_target)
print(f'training_score : {lasso.score(train_scaled, train_target)}')
print(f'test_score : {lasso.score(test_scaled, test_target)}')

In [ ]:
lasso = Lasso(10000)
lasso.fit(train_scaled, train_target)
print(f'training_score : {lasso.score(train_scaled, train_target)}')
print(f'test_score : {lasso.score(test_scaled, test_target)}')