In [1]:
import pandas as pd
import numpy as np

In [2]:
input_file = 'kakao_review.csv'
output_file = 'kakao_review_result.csv'
df_kakao = pd.read_csv(input_file)
df_kakao

,WRITER,CONTENT,TYPE,SCORE,CREATED_AT,RENTAL_CAR_ID
0,자연인 주나,쿱카를 통해 제주로렌트카 차량을 배정받았는데 차 정비를 안하시는 듯(2021.12....,카카오맵,1,21.12.31.,제주도렌트카협동조합
1,.,NaN,카카오맵,1,21.10.01.,제주도렌트카협동조합
2,두아이맘,렌터카카 2000키로도 안된 새차. 주행감도 좋아 기분좋은 여행 했습니다. 다만 ...,카카오맵,5,20.08.15.,제주도렌트카협동조합
3,JS쿠마,정말 제주도렌트카협동조합 덕분에 아주 기분좋은여행이었습니다~^^직원분들도 친절하시고...,카카오맵,5,20.08.14.,제주도렌트카협동조합
4,석,정말 편리하고 싸게 잘 이용했습니다. 미리 등록해 놓으니 무인인수라 인수도 굉장히 ...,카카오맵,5,20.05.28.,제주도렌트카협동조합
...,...,...,...,...,...,...
2854,강,A MEN YO(__),카카오맵,5,20.12.22.,제주국제공항 렌터카하우스
2855,.,셔틀버스 자리가 헷갈려서 8구역에 계시는 직원분께 여쭤봤는데 '제대로 알고 물어봐야...,카카오맵,1,20.01.21.,제주국제공항 렌터카하우스
2856,피트니스럽,불친절하고 이럴 거면 종합으로 왜 세워놨나 싶음. 일하는 남자 직원은 일하기 싫은 ...,카카오맵,1,19.09.23.,제주국제공항 렌터카하우스
2857,Александр,NaN,카카오맵,5,19.08.08.,제주국제공항 렌터카하우스
2858,동그라미,다른 렌트카에 비해서는 쌉니다. 그런데 타시기 전에 사진 꼭 잘 찍어두세요. 출고전...,카카오맵,2,22.08.19.,타시오렌트카

In [3]:
df_kakao['RENTAL_CAR_ID'].value_counts().head(50)

무지개렌트카             160
로그인렌트카             152
블루렌트카              127
퍼시픽렌터카 제주지점        127
스타렌트카              107
특별한렌트카              92
탐라렌트카               91
조아렌트카               90
아리랑렌트카              88
제주로렌트카              84
SK렌터카 제주지점          82
패밀리렌트카              77
제주엔젤렌트카             72
제주렌트카 본사            62
제주현대렌트카             62
롯데렌터카 제주오토하우스지점     59
KD렌트카               58
제주공항렌트카 본사          54
한국렌트카               53
제주다움렌터카             51
수렌트카                48
예스렌트카               48
제주아산렌트카             48
보고타렌터카              44
레드캡렌터카 제주지점         42
뉴대한렌트카              41
제주사랑렌트카             40
퍼스트렌트카              39
자유렌트카               37
에이스렌트카              30
해피렌트카               28
라인렌트카               26
씨유렌트카               25
뉴제주렌터카              24
굿모닝렌트카              24
우도전기렌트카             23
제주한라렌트카             23
가자제주렌트카             22
발리렌트카               22
신동아렌터카              21
땡큐제주렌트카             21
더세븐렌트카              20
매일렌트카               19
더세이프렌터카             18
제주알프스렌터카            18
제주타요렌터카             17
우도사람들렌트             16
올레렌트카               16
제주삼성렌트카             15
오라렌트카               15
Name: RENTAL_CAR_ID, dtype: int64

In [4]:
df_kakao['RENTAL_CAR_ID'].unique()

array(['제주도렌트카협동조합', '무지개렌트카', '탐라렌트카', '제주렌트카 본사', '제주엔젤렌트카', '조아렌트카',
       '로그인렌트카', '퍼스트렌트카', '패밀리렌트카', '블루렌트카', '하나렌트카', '스타렌트카', '제주현대렌트카',
       '아리랑렌트카', '한국렌트카', '라인렌트카', '특별한렌트카', '오렌지렌트카', '수렌트카', '예스렌트카',
       'KD렌트카', '씨유렌트카', '해피렌트카', '제주한라렌트카', '레츠고렌트카', '땡큐제주렌트카', '올레렌트카',
       '뉴대한렌트카', '자유렌트카', '제주사랑렌트카', '디렌트카', '돌하루팡렌트카', '썬렌트카', '한라산렌트카',
       '가자제주렌트카', '용두암렌트카', '매일렌트카', '제주아산렌트카', '제주드림렌트카', '굿모닝렌트카',
       '더세븐렌트카', '제주공항렌트카 본사', '제주명품렌트카', '에스제이렌트카', '제주평화렌트카', '발리렌트카',
       '에이스렌트카', '제주패스렌트카', '제주삼성렌트카', '제주원렌트카 본점', '장수렌트카', '제주프리렌트카',
       '오라렌트카', '차세대렌트카 제주오토하우스', '통일렌트카', '금강렌트카', '제주더렌트카', '메트로렌트카(주)',
       '제주제일렌트카 제주지점', '우도전기렌트카', '일번렌트카', 'EV전기렌트카', '제일렌트카 공항점',
       '제주베스트렌트카', '제주렌트카 공항지점', '제주에코렌트카', '유명렌트카', '파워렌트카', 'DR렌트카',
       '로얄렌트카', '제주야렌트카', '힐렌트카', '롯데렌터카 제주오토하우스지점', 'SK렌터카 제주지점',
       '레드캡렌터카 제주지점', '제주다움렌터카', '보고타렌터카', '퍼시픽렌터카 제주지점', '제주알프스렌터카',
       '롯데렌터카 제주중문롯데호텔지점', '뉴제주렌터카', '더세이프렌터카', '신동아렌터카', '제주타요렌터카',
       '갤럭시렌터카', '녹원렌터카', '한길렌터카', '한진렌터카', '로보트렌터카', '식스트렌터카 제주지점',
       '제주로렌트카', '우도사람들렌트', '현대렌트', '우도렌트', '제주국제공항 렌터카하우스', '타시오렌트카'],
      dtype=object)

In [5]:
input_file2 = '제주도_렌터카업체위치.xlsx'
data_frame = pd.read_excel(input_file2, sheet_name='제주도_렌터카업체위치 (1)')
data_frame

,id,업체명,사업장구분,소재지도로명주소,소재지지번주소,위도,경도,차고지도로명주소,차고지지번주소,보유차고지수용능력,...,평일운영시작시각,평일운영종료시각,주말운영시작시각,주말운영종료시각,홈페이지주소,전화번호,데이터기준일자,네이버 평점,구글 평점,카카오 평점
0,1,에스카렌트카,주사업장,제주특별자치도 제주시 연미길 42,제주특별자치도 제주시 오라삼동 2854-2,33.490170,126.505583,제주특별자치도 제주시 연미길 42,NaN,NaN,...,07:45:00,20:00:00,08:00:00,20:00:00,http://carmap.co.kr/web/mplus/jumpo/mview.php?...,070-4352-5515,2022-12-01,NaN,NaN,NaN
1,2,더세이프렌터카,주사업장,제주특별자치도 제주시 용문로 88,제주특별자치도 제주시 용담이동 2739,33.503443,126.505186,제주특별자치도 제주시 용문로 88,NaN,NaN,...,08:00:00,20:00:00,08:00:00,20:00:00,https://www.interparkrentcar.com,064-743-1515,2022-12-01,NaN,NaN,NaN
2,3,아리랑렌트카,주사업장,제주특별자치도 제주시 용마서길 34,제주특별자치도 제주시 용담삼동 970-3,33.514957,126.502067,제주특별자치도 제주시 용담3동 969-3,NaN,NaN,...,08:00:00,20:00:00,08:00:00,20:00:00,http://www.newarirang.co.kr/,064-749-2139,2022-12-01,NaN,NaN,NaN
3,4,제주아산렌트카,주사업장,제주특별자치도 제주시 연미길 44,제주특별자치도 제주시 오라삼동 2853-1,33.489788,126.505795,제주특별자치도 제주시 오라3동 2853-1,NaN,NaN,...,08:00:00,20:00:00,08:00:00,20:00:00,https://jjasan.com/,064-743-9991,2022-12-01,NaN,NaN,NaN
4,5,한국렌트카,주사업장,제주특별자치도 제주시 연미길 53,제주특별자치도 제주시 오라이동 2826-1,33.488469,126.505530,제주특별자치도 제주시 연미길 53,NaN,NaN,...,08:00:00,20:00:00,08:00:00,20:00:00,http://www.hanrent.co.kr/,064-748-5005,2022-12-01,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,110,스타렌트카,영업소,제주특별자치도 제주시 용문로 20,제주특별자치도 제주시 용담이동 1524-12,33.504892,126.498397,제주특별자치도 제주시 용담2동 1524-12,NaN,NaN,...,08:00:00,20:00:00,08:00:00,20:00:00,https://jejustar.co.kr/,064-759-3372,2022-12-01,NaN,NaN,NaN
111,111,제일렌트카 공항점,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
112,111,제주제일렌트카 제주지점,영업소,제주특별자치도 제주시 월성로4길 78,제주특별자치도 제주시 용담이동 1730-4,33.498428,126.498207,제주특별자치도 제주시 애월읍 상귀리 679-1,NaN,NaN,...,08:00:00,20:00:00,08:00:00,20:00:00,http://jejubestrent.com/,064-747-5670,2022-12-01,NaN,NaN,NaN
113,112,해피렌트카,영업소,제주특별자치도 제주시 일주서로 7581,제주특별자치도 제주시 이호이동 1606,33.495760,126.456506,제주특별자치도 제주시 노형동 3744-4,NaN,NaN,...,08:00:00,20:00:00,08:00:00,20:00:00,NaN,064-711-7935,2022-12-01,NaN,NaN,NaN
114,113,퍼시픽렌터카 제주지점,영업소,제주특별자치도 제주시 월성로4길 74-12,제주특별자치도 제주시 용담이동 1673-1,33.499355,126.498447,제주특별자치도 제주시 일주서로 7822,NaN,NaN,...,08:00:00,20:00:00,08:00:00,20:00:00,http://www.pacificrentcar.co.kr/main.asp?,064-747-1541,2022-12-01,NaN,NaN,NaN

In [6]:
df = data_frame.iloc[:,:2]
df

      id           업체명
0      1        에스카렌트카
1      2       더세이프렌터카
2      3        아리랑렌트카
3      4       제주아산렌트카
4      5         한국렌트카
..   ...           ...
110  110         스타렌트카
111  111     제일렌트카 공항점
112  111  제주제일렌트카 제주지점
113  112         해피렌트카
114  113   퍼시픽렌터카 제주지점

[115 rows x 2 columns]

In [7]:
df['업체명'].unique()

array(['에스카렌트카', '더세이프렌터카', '아리랑렌트카', '제주아산렌트카', '한국렌트카', '탐라렌트카',
       '써니빌렌트카', '용두암렌트카', '장수렌트카', '가자제주렌트카', '오름렌트카', '제주렌트카 본사',
       '제주오케이렌터카', '뉴제주렌터카', '굿모닝렌트카', '제주공항렌트카 본사', '메트로렌트카㈜', '한길렌터카',
       '대진렌트카', '발리렌트카', '렌트파크', '하나렌트카', '행운렌트카', '제주사랑렌트카', '한라산렌트카',
       '특별한렌트카', '올레렌트카', '제주드림렌트카', '제주여행렌트카', '제주타요렌터카', '좋은렌트카',
       'KD렌트카', '제주평화렌트카', '제주현대렌트카', '쏘카', '썬렌트카', '스마트렌트카', '무지개렌트카',
       '뉴대한렌트카', '우리렌트카', '공항렌트카', '레츠고렌트카', '퍼스트렌트카', '통일렌트카', '더세븐렌트카',
       '에스제이렌트카', '메이저렌트카', '제주로렌트카', '제주유명렌트카', '조아렌트카', '에이스렌트카',
       '오라렌트카', '제주삼성렌트카', '예스렌트카', '제주한라렌트카', '제주자연렌트카', '디렌트카',
       '제주카카오렌트카', '하이제주렌트카', '제주명품렌트카', '씨유렌트카', '제주엔젤렌트카', '오렌지렌트카',
       '로그인렌트카', '씨카', '패밀리렌트카', '자유렌터카', '수렌트카', '제주카카', '땡큐제주렌트카',
       '뉴제주콜렌트카', '제주다움렌터카', '로얄렌트카', '블루렌트카', '로보트렌터카', '제주베스트렌트카',
       '제주알프스렌터카', '파워렌트카', '제주공항전기차', '우도전기렌트카', '제주아이렌트카', '라인렌트카',
       '자보렌트카', '제주원렌트카 본점', '매일렌트카', '비비카', '제주유레카', '스마일렌트카', '녹원렌터카',
       '보고타렌터카', '플러스제주렌트카', '레인보우모빌리티', '디알', '제주이브이전기렌트카', '제이공항렌트카',
       '제이테크인', '금강렌트카', '하이렌터카', '국제렌트카', '신동아렌터카', '에스티홀딩스', '일출렌터카',
       '소풍렌트카', '제주동백렌트카', '롯데렌터카 제주중문롯데호텔지점', '롯데렌터카 제주오토하우스지점',
       '차세대렌트카 제주오토하우스', 'SK렌터카 제주지점', '경동렌트카', '레드캡렌터카 제주지점', '스타렌트카',
       '제일렌트카 공항점', '제주제일렌트카 제주지점', '해피렌트카', '퍼시픽렌터카 제주지점'], dtype=object)

In [8]:
df_kakao['RENTAL_CAR_ID'].unique()

array(['제주도렌트카협동조합', '무지개렌트카', '탐라렌트카', '제주렌트카 본사', '제주엔젤렌트카', '조아렌트카',
       '로그인렌트카', '퍼스트렌트카', '패밀리렌트카', '블루렌트카', '하나렌트카', '스타렌트카', '제주현대렌트카',
       '아리랑렌트카', '한국렌트카', '라인렌트카', '특별한렌트카', '오렌지렌트카', '수렌트카', '예스렌트카',
       'KD렌트카', '씨유렌트카', '해피렌트카', '제주한라렌트카', '레츠고렌트카', '땡큐제주렌트카', '올레렌트카',
       '뉴대한렌트카', '자유렌트카', '제주사랑렌트카', '디렌트카', '돌하루팡렌트카', '썬렌트카', '한라산렌트카',
       '가자제주렌트카', '용두암렌트카', '매일렌트카', '제주아산렌트카', '제주드림렌트카', '굿모닝렌트카',
       '더세븐렌트카', '제주공항렌트카 본사', '제주명품렌트카', '에스제이렌트카', '제주평화렌트카', '발리렌트카',
       '에이스렌트카', '제주패스렌트카', '제주삼성렌트카', '제주원렌트카 본점', '장수렌트카', '제주프리렌트카',
       '오라렌트카', '차세대렌트카 제주오토하우스', '통일렌트카', '금강렌트카', '제주더렌트카', '메트로렌트카(주)',
       '제주제일렌트카 제주지점', '우도전기렌트카', '일번렌트카', 'EV전기렌트카', '제일렌트카 공항점',
       '제주베스트렌트카', '제주렌트카 공항지점', '제주에코렌트카', '유명렌트카', '파워렌트카', 'DR렌트카',
       '로얄렌트카', '제주야렌트카', '힐렌트카', '롯데렌터카 제주오토하우스지점', 'SK렌터카 제주지점',
       '레드캡렌터카 제주지점', '제주다움렌터카', '보고타렌터카', '퍼시픽렌터카 제주지점', '제주알프스렌터카',
       '롯데렌터카 제주중문롯데호텔지점', '뉴제주렌터카', '더세이프렌터카', '신동아렌터카', '제주타요렌터카',
       '갤럭시렌터카', '녹원렌터카', '한길렌터카', '한진렌터카', '로보트렌터카', '식스트렌터카 제주지점',
       '제주로렌트카', '우도사람들렌트', '현대렌트', '우도렌트', '제주국제공항 렌터카하우스', '타시오렌트카'],
      dtype=object)

In [9]:
df2 = pd.merge(df, df_kakao, how='inner', left_on = '업체명', right_on = 'RENTAL_CAR_ID')
df2

,id,업체명,WRITER,CONTENT,TYPE,SCORE,CREATED_AT,RENTAL_CAR_ID
0,2,더세이프렌터카,미식가고양이,거짓후기인가... 직원분들 모두 친절하고 셔틀도 바로 오시던데 신차급차량과 렌트비도...,카카오맵,5,22.11.20.,더세이프렌터카
1,2,더세이프렌터카,♤♡♤,별도 아깝네요. 그래도 다른 여직원분은 설명도 잘해주시고 친절했는데 반납할때 다른 ...,카카오맵,1,22.11.05.,더세이프렌터카
2,2,더세이프렌터카,ㅇㅇ,별하나도 아깝네요 불친절에 바가지 지대로고요 다시는 안갈듯. 기분좋게 여행하려 수...,카카오맵,1,22.08.24.,더세이프렌터카
3,2,더세이프렌터카,클리너,"원래 이런거 귀찮아서 안올리는데, 혹시 저와 같은 피해자가 또 생길까 봐서 참고하...",카카오맵,1,22.07.19.,더세이프렌터카
4,2,더세이프렌터카,도라이몽,카운터에 있는 여자남자 둘다 진짜 심각함. 제주도 촌이라서 아무나 쓰는 건지.. 사...,카카오맵,1,22.03.08.,더세이프렌터카
...,...,...,...,...,...,...,...,...
2694,113,퍼시픽렌터카 제주지점,거긴어디,다신 안감,카카오맵,1,19.06.26.,퍼시픽렌터카 제주지점
2695,113,퍼시픽렌터카 제주지점,Leeyongsook,별 하나도 아까운 곳~<br/>서비스 개엉망에 졸싸가지없는여직원<br/>렌트카하나때...,카카오맵,1,19.06.15.,퍼시픽렌터카 제주지점
2696,113,퍼시픽렌터카 제주지점,♡행복한사람♡,퍼시픽렌트카에서 K7 빌려서 여행 3일째 저녁에 공기압 떴어요.<br/>저흰 완전자...,카카오맵,1,19.06.10.,퍼시픽렌터카 제주지점
2697,113,퍼시픽렌터카 제주지점,정재용,계약서에 기입한 기름 퍼센티지 정확히 확인바람.출발전 찍은 기름양만큼 넣지만 기름양...,카카오맵,1,19.06.01.,퍼시픽렌터카 제주지점
2698,113,퍼시픽렌터카 제주지점,서동일,NaN,카카오맵,2,19.04.27.,퍼시픽렌터카 제주지점

In [10]:
df3 = df2.drop(['업체명','RENTAL_CAR_ID'],axis=1)
df3

,id,WRITER,CONTENT,TYPE,SCORE,CREATED_AT
0,2,미식가고양이,거짓후기인가... 직원분들 모두 친절하고 셔틀도 바로 오시던데 신차급차량과 렌트비도...,카카오맵,5,22.11.20.
1,2,♤♡♤,별도 아깝네요. 그래도 다른 여직원분은 설명도 잘해주시고 친절했는데 반납할때 다른 ...,카카오맵,1,22.11.05.
2,2,ㅇㅇ,별하나도 아깝네요 불친절에 바가지 지대로고요 다시는 안갈듯. 기분좋게 여행하려 수...,카카오맵,1,22.08.24.
3,2,클리너,"원래 이런거 귀찮아서 안올리는데, 혹시 저와 같은 피해자가 또 생길까 봐서 참고하...",카카오맵,1,22.07.19.
4,2,도라이몽,카운터에 있는 여자남자 둘다 진짜 심각함. 제주도 촌이라서 아무나 쓰는 건지.. 사...,카카오맵,1,22.03.08.
...,...,...,...,...,...,...
2694,113,거긴어디,다신 안감,카카오맵,1,19.06.26.
2695,113,Leeyongsook,별 하나도 아까운 곳~<br/>서비스 개엉망에 졸싸가지없는여직원<br/>렌트카하나때...,카카오맵,1,19.06.15.
2696,113,♡행복한사람♡,퍼시픽렌트카에서 K7 빌려서 여행 3일째 저녁에 공기압 떴어요.<br/>저흰 완전자...,카카오맵,1,19.06.10.
2697,113,정재용,계약서에 기입한 기름 퍼센티지 정확히 확인바람.출발전 찍은 기름양만큼 넣지만 기름양...,카카오맵,1,19.06.01.
2698,113,서동일,NaN,카카오맵,2,19.04.27.

In [11]:
df4 = df3.rename(columns={'id':'RENTAL_CAR_ID'})
df4

,RENTAL_CAR_ID,WRITER,CONTENT,TYPE,SCORE,CREATED_AT
0,2,미식가고양이,거짓후기인가... 직원분들 모두 친절하고 셔틀도 바로 오시던데 신차급차량과 렌트비도...,카카오맵,5,22.11.20.
1,2,♤♡♤,별도 아깝네요. 그래도 다른 여직원분은 설명도 잘해주시고 친절했는데 반납할때 다른 ...,카카오맵,1,22.11.05.
2,2,ㅇㅇ,별하나도 아깝네요 불친절에 바가지 지대로고요 다시는 안갈듯. 기분좋게 여행하려 수...,카카오맵,1,22.08.24.
3,2,클리너,"원래 이런거 귀찮아서 안올리는데, 혹시 저와 같은 피해자가 또 생길까 봐서 참고하...",카카오맵,1,22.07.19.
4,2,도라이몽,카운터에 있는 여자남자 둘다 진짜 심각함. 제주도 촌이라서 아무나 쓰는 건지.. 사...,카카오맵,1,22.03.08.
...,...,...,...,...,...,...
2694,113,거긴어디,다신 안감,카카오맵,1,19.06.26.
2695,113,Leeyongsook,별 하나도 아까운 곳~<br/>서비스 개엉망에 졸싸가지없는여직원<br/>렌트카하나때...,카카오맵,1,19.06.15.
2696,113,♡행복한사람♡,퍼시픽렌트카에서 K7 빌려서 여행 3일째 저녁에 공기압 떴어요.<br/>저흰 완전자...,카카오맵,1,19.06.10.
2697,113,정재용,계약서에 기입한 기름 퍼센티지 정확히 확인바람.출발전 찍은 기름양만큼 넣지만 기름양...,카카오맵,1,19.06.01.
2698,113,서동일,NaN,카카오맵,2,19.04.27.

In [12]:
df5 = df4[['WRITER','CONTENT','TYPE','SCORE','CREATED_AT','RENTAL_CAR_ID']]
df5

,WRITER,CONTENT,TYPE,SCORE,CREATED_AT,RENTAL_CAR_ID
0,미식가고양이,거짓후기인가... 직원분들 모두 친절하고 셔틀도 바로 오시던데 신차급차량과 렌트비도...,카카오맵,5,22.11.20.,2
1,♤♡♤,별도 아깝네요. 그래도 다른 여직원분은 설명도 잘해주시고 친절했는데 반납할때 다른 ...,카카오맵,1,22.11.05.,2
2,ㅇㅇ,별하나도 아깝네요 불친절에 바가지 지대로고요 다시는 안갈듯. 기분좋게 여행하려 수...,카카오맵,1,22.08.24.,2
3,클리너,"원래 이런거 귀찮아서 안올리는데, 혹시 저와 같은 피해자가 또 생길까 봐서 참고하...",카카오맵,1,22.07.19.,2
4,도라이몽,카운터에 있는 여자남자 둘다 진짜 심각함. 제주도 촌이라서 아무나 쓰는 건지.. 사...,카카오맵,1,22.03.08.,2
...,...,...,...,...,...,...
2694,거긴어디,다신 안감,카카오맵,1,19.06.26.,113
2695,Leeyongsook,별 하나도 아까운 곳~<br/>서비스 개엉망에 졸싸가지없는여직원<br/>렌트카하나때...,카카오맵,1,19.06.15.,113
2696,♡행복한사람♡,퍼시픽렌트카에서 K7 빌려서 여행 3일째 저녁에 공기압 떴어요.<br/>저흰 완전자...,카카오맵,1,19.06.10.,113
2697,정재용,계약서에 기입한 기름 퍼센티지 정확히 확인바람.출발전 찍은 기름양만큼 넣지만 기름양...,카카오맵,1,19.06.01.,113
2698,서동일,NaN,카카오맵,2,19.04.27.,113

In [13]:
df6 = df5.copy()

In [14]:
df6

,WRITER,CONTENT,TYPE,SCORE,CREATED_AT,RENTAL_CAR_ID
0,미식가고양이,거짓후기인가... 직원분들 모두 친절하고 셔틀도 바로 오시던데 신차급차량과 렌트비도...,카카오맵,5,22.11.20.,2
1,♤♡♤,별도 아깝네요. 그래도 다른 여직원분은 설명도 잘해주시고 친절했는데 반납할때 다른 ...,카카오맵,1,22.11.05.,2
2,ㅇㅇ,별하나도 아깝네요 불친절에 바가지 지대로고요 다시는 안갈듯. 기분좋게 여행하려 수...,카카오맵,1,22.08.24.,2
3,클리너,"원래 이런거 귀찮아서 안올리는데, 혹시 저와 같은 피해자가 또 생길까 봐서 참고하...",카카오맵,1,22.07.19.,2
4,도라이몽,카운터에 있는 여자남자 둘다 진짜 심각함. 제주도 촌이라서 아무나 쓰는 건지.. 사...,카카오맵,1,22.03.08.,2
...,...,...,...,...,...,...
2694,거긴어디,다신 안감,카카오맵,1,19.06.26.,113
2695,Leeyongsook,별 하나도 아까운 곳~<br/>서비스 개엉망에 졸싸가지없는여직원<br/>렌트카하나때...,카카오맵,1,19.06.15.,113
2696,♡행복한사람♡,퍼시픽렌트카에서 K7 빌려서 여행 3일째 저녁에 공기압 떴어요.<br/>저흰 완전자...,카카오맵,1,19.06.10.,113
2697,정재용,계약서에 기입한 기름 퍼센티지 정확히 확인바람.출발전 찍은 기름양만큼 넣지만 기름양...,카카오맵,1,19.06.01.,113
2698,서동일,NaN,카카오맵,2,19.04.27.,113

In [15]:
df6.reset_index(inplace=True)

In [16]:
df6

,index,WRITER,CONTENT,TYPE,SCORE,CREATED_AT,RENTAL_CAR_ID
0,0,미식가고양이,거짓후기인가... 직원분들 모두 친절하고 셔틀도 바로 오시던데 신차급차량과 렌트비도...,카카오맵,5,22.11.20.,2
1,1,♤♡♤,별도 아깝네요. 그래도 다른 여직원분은 설명도 잘해주시고 친절했는데 반납할때 다른 ...,카카오맵,1,22.11.05.,2
2,2,ㅇㅇ,별하나도 아깝네요 불친절에 바가지 지대로고요 다시는 안갈듯. 기분좋게 여행하려 수...,카카오맵,1,22.08.24.,2
3,3,클리너,"원래 이런거 귀찮아서 안올리는데, 혹시 저와 같은 피해자가 또 생길까 봐서 참고하...",카카오맵,1,22.07.19.,2
4,4,도라이몽,카운터에 있는 여자남자 둘다 진짜 심각함. 제주도 촌이라서 아무나 쓰는 건지.. 사...,카카오맵,1,22.03.08.,2
...,...,...,...,...,...,...,...
2694,2694,거긴어디,다신 안감,카카오맵,1,19.06.26.,113
2695,2695,Leeyongsook,별 하나도 아까운 곳~<br/>서비스 개엉망에 졸싸가지없는여직원<br/>렌트카하나때...,카카오맵,1,19.06.15.,113
2696,2696,♡행복한사람♡,퍼시픽렌트카에서 K7 빌려서 여행 3일째 저녁에 공기압 떴어요.<br/>저흰 완전자...,카카오맵,1,19.06.10.,113
2697,2697,정재용,계약서에 기입한 기름 퍼센티지 정확히 확인바람.출발전 찍은 기름양만큼 넣지만 기름양...,카카오맵,1,19.06.01.,113
2698,2698,서동일,NaN,카카오맵,2,19.04.27.,113

In [17]:
df6.rename(columns={'index':'ID'},inplace=True)

In [18]:
df6

,ID,WRITER,CONTENT,TYPE,SCORE,CREATED_AT,RENTAL_CAR_ID
0,0,미식가고양이,거짓후기인가... 직원분들 모두 친절하고 셔틀도 바로 오시던데 신차급차량과 렌트비도...,카카오맵,5,22.11.20.,2
1,1,♤♡♤,별도 아깝네요. 그래도 다른 여직원분은 설명도 잘해주시고 친절했는데 반납할때 다른 ...,카카오맵,1,22.11.05.,2
2,2,ㅇㅇ,별하나도 아깝네요 불친절에 바가지 지대로고요 다시는 안갈듯. 기분좋게 여행하려 수...,카카오맵,1,22.08.24.,2
3,3,클리너,"원래 이런거 귀찮아서 안올리는데, 혹시 저와 같은 피해자가 또 생길까 봐서 참고하...",카카오맵,1,22.07.19.,2
4,4,도라이몽,카운터에 있는 여자남자 둘다 진짜 심각함. 제주도 촌이라서 아무나 쓰는 건지.. 사...,카카오맵,1,22.03.08.,2
...,...,...,...,...,...,...,...
2694,2694,거긴어디,다신 안감,카카오맵,1,19.06.26.,113
2695,2695,Leeyongsook,별 하나도 아까운 곳~<br/>서비스 개엉망에 졸싸가지없는여직원<br/>렌트카하나때...,카카오맵,1,19.06.15.,113
2696,2696,♡행복한사람♡,퍼시픽렌트카에서 K7 빌려서 여행 3일째 저녁에 공기압 떴어요.<br/>저흰 완전자...,카카오맵,1,19.06.10.,113
2697,2697,정재용,계약서에 기입한 기름 퍼센티지 정확히 확인바람.출발전 찍은 기름양만큼 넣지만 기름양...,카카오맵,1,19.06.01.,113
2698,2698,서동일,NaN,카카오맵,2,19.04.27.,113

In [19]:
df6.fillna(' ',inplace=True)

In [20]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2699 entries, 0 to 2698
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             2699 non-null   int64
 1   WRITER         2699 non-null   object
 2   CONTENT        2699 non-null   object
 3   TYPE           2699 non-null   object
 4   SCORE          2699 non-null   int64
 5   CREATED_AT     2699 non-null   object
 6   RENTAL_CAR_ID  2699 non-null   int64
dtypes: int64(3), object(4)
memory usage: 147.7+ KB

In [21]:
df6['CONTENT']=df6['CONTENT'].str.replace('<br/>','')

In [22]:
df6

,ID,WRITER,CONTENT,TYPE,SCORE,CREATED_AT,RENTAL_CAR_ID
0,0,미식가고양이,거짓후기인가... 직원분들 모두 친절하고 셔틀도 바로 오시던데 신차급차량과 렌트비도...,카카오맵,5,22.11.20.,2
1,1,♤♡♤,별도 아깝네요. 그래도 다른 여직원분은 설명도 잘해주시고 친절했는데 반납할때 다른 ...,카카오맵,1,22.11.05.,2
2,2,ㅇㅇ,별하나도 아깝네요 불친절에 바가지 지대로고요 다시는 안갈듯. 기분좋게 여행하려 수...,카카오맵,1,22.08.24.,2
3,3,클리너,"원래 이런거 귀찮아서 안올리는데, 혹시 저와 같은 피해자가 또 생길까 봐서 참고하...",카카오맵,1,22.07.19.,2
4,4,도라이몽,카운터에 있는 여자남자 둘다 진짜 심각함. 제주도 촌이라서 아무나 쓰는 건지.. 사...,카카오맵,1,22.03.08.,2
...,...,...,...,...,...,...,...
2694,2694,거긴어디,다신 안감,카카오맵,1,19.06.26.,113
2695,2695,Leeyongsook,별 하나도 아까운 곳~서비스 개엉망에 졸싸가지없는여직원렌트카하나때문에 기분 바가지로...,카카오맵,1,19.06.15.,113
2696,2696,♡행복한사람♡,퍼시픽렌트카에서 K7 빌려서 여행 3일째 저녁에 공기압 떴어요.저흰 완전자차만했는데...,카카오맵,1,19.06.10.,113
2697,2697,정재용,계약서에 기입한 기름 퍼센티지 정확히 확인바람.출발전 찍은 기름양만큼 넣지만 기름양...,카카오맵,1,19.06.01.,113
2698,2698,서동일,,카카오맵,2,19.04.27.,113

In [23]:
df6.shape

(2699, 7)

In [46]:
df6.to_csv(output_file, index = False, encoding = 'utf-8')