In [1]:
import pandas as pd
import numpy as np

musicData = pd.read_csv('../data/musicData.csv', encoding='UTF-8')
musicData2 = pd.read_csv('../data/musicData2.csv', encoding='UTF-8')

In [2]:
music_i = musicData.set_index(['Date'])
music_i

,Album Title,Artist Name,Genre,Distribution,Rating,Music Count
Date,,,,,,
2018.09.01,거기가 어딘데?? OST,Various Artists,O.S.T,워너뮤직코리아,6.4,8
2018.09.01,얍,갈릭스(Garlixx),"인디뮤직, 락",(주)미러볼뮤직,3.8,2
2018.09.01,너와 나,파란,발라드,(주)지니뮤직,7.7,2
2018.09.01,PRODUCE 48 - FINAL,PRODUCE 48,댄스,Stone Music Entertainment,7.0,4
2018.09.01,Weather : 오늘 당신의 날씨는 어떤가요? Part 4,이진아,재즈,(주)지니뮤직,6.7,1
...,...,...,...,...,...,...
2018.10.11,It's a TRAP!,넘넘(numnum),"인디뮤직, 락",포크라노스,0.0,1
2018.10.11,Kryptonite (크립토나이트),Seiren(세이렌),랩/힙합,퍼플파인엔터테인먼트,0.0,1
2018.10.11,"Sandwich, Milk (Feat. divin')",C.Koon,랩/힙합,(주)아이리버,0.0,1
2018.10.11,손 the guest OST Part 2,손승연,드라마음악,Stone Music Entertainment,9.0,2
2018.10.11,꽃처럼,페르시(persie),발라드,아토엔터테인먼트,0.0,1

In [3]:
music2_i = musicData2.set_index('Date')
music2_i

,Year,Month,Album Title,Artist Name,Genre,Distribution,Rating,Music Count
Date,,,,,,,,
2017.01.25,2017,1,Boys and Girls Music Vol. 1,샘김,알앤비/어반,로엔 엔터테인먼트,8.6,2
2016.07.11,2017,1,여자친구 The 1st Album 'LOL',여자친구(GFRIEND),댄스,로엔엔터테인먼트,8.1,12
2016.11.05,2017,1,Collage (EP),The Chainsmokers,일렉트로니카,소니뮤직,7.5,5
2016.08.23,2017,1,If You,에일리,발라드,로엔 엔터테인먼트,6.9,1
2016.10.07,2017,1,세 단어,젝스키스,발라드,YG PLUS,9.0,1
...,...,...,...,...,...,...,...,...
2018.05.08,2018,10,RECIPE,벤,발라드,(주)지니뮤직,7.1,10
2018.03.12,2018,10,Eyes On You,GOT7 (갓세븐),"댄스, 알앤비/어반",(주)아이리버,8.6,7
2018.06.27,2018,10,Take,숀(SHAUN),"일렉트로니카, 인디뮤직",워너뮤직코리아,3.7,4
2018.09.18,2018,10,우리 그만하자,로이킴,발라드,(주)지니뮤직,7.0,2
2018.09.19,2018,10,하루도 그대를 사랑하지 않은 적이 없었다,임창정,"발라드, 댄스",(주)인터파크,8.5,14

<hr> 
<hr>

# 문제 1
- 상단의 데이터프레임 2개를 inner join 하시오.
- 중복 되는 열 이름은 구별 되게 출력 하시오

In [4]:
music_join = music_i.join(music2_i,how='inner',rsuffix='_new')
music_join.head()

,Album Title,Artist Name,Genre,Distribution,Rating,Music Count,Year,Month,Album Title_new,Artist Name_new,Genre_new,Distribution_new,Rating_new,Music Count_new
Date,,,,,,,,,,,,,,
2018.09.03,하늘엔 별이 떠있고 너만큼은 빛나질 않아,이민혁,"발라드, 인디뮤직",워너뮤직코리아,8.6,1,2018,9,Second Write..,남우현,발라드,로엔엔터테인먼트,9.7,7
2018.09.03,역병,스톤엑스,락,(주)뮤즈플랫폼,1.0,1,2018,9,Second Write..,남우현,발라드,로엔엔터테인먼트,9.7,7
2018.09.03,2018 월간 윤종신 9월호,윤종신,발라드,(주)아이리버,8.3,1,2018,9,Second Write..,남우현,발라드,로엔엔터테인먼트,9.7,7
2018.09.03,원츄,캔(Can),"락, 댄스",(주)뮤직앤뉴,5.0,3,2018,9,Second Write..,남우현,발라드,로엔엔터테인먼트,9.7,7
2018.09.03,복수노트2 OST Part.2,필독,드라마음악,(주)블렌딩,7.8,1,2018,9,Second Write..,남우현,발라드,로엔엔터테인먼트,9.7,7

 <hr> 
<hr>

# 문제 2
- 문제 1의 결과를 이용하여 Album Title 과 Artist Name, Rating을 고정열로 설정하여 Genre 열 두개를 병합 처리하여 출력 하시오.
- 변수명은 자유롭게 설정 하되, melt 함수 사용 하시오

In [5]:
music_genre = music_join.melt(id_vars = ['Album Title','Artist Name','Rating'], var_name = "melt_Genre", value_name = "genre", value_vars=['Genre','Genre_new'])

music_genre

                 Album Title Artist Name  Rating melt_Genre       genre
0     하늘엔 별이 떠있고 너만큼은 빛나질 않아         이민혁     8.6      Genre  발라드,  인디뮤직
1                         역병        스톤엑스     1.0      Genre           락
2            2018 월간 윤종신 9월호         윤종신     8.3      Genre         발라드
3                         원츄      캔(Can)     5.0      Genre      락,  댄스
4           복수노트2 OST Part.2          필독     7.8      Genre       드라마음악
...                      ...         ...     ...        ...         ...
3137  미스마, 복수의 여신 OST Part 1          제아     4.3  Genre_new        랩/힙합
3138                      #7       세븐어클락     5.0  Genre_new        랩/힙합
3139                      #7       세븐어클락     5.0  Genre_new        랩/힙합
3140               Love Song         박소유     5.9  Genre_new        랩/힙합
3141               Love Song         박소유     5.9  Genre_new        랩/힙합

[3142 rows x 5 columns]

<hr> 
<hr>

<table>
    <tr>
     <td>
        <a href="https://hong-dev.github.io/gopizza/rank_tie/"><font size="5" color="red">순위 메서드 정리 잘 되있는 사이트</font></a>
        </td>
    </tr>
</table>

# 보너스 문제
- 문제 2의 결과에 Rating 열을 기반으로 순위 열을 만드시오.
- 단, 동점인 데이터는 데이터 상에서 먼저 나타나는 관측치부터 우선 순위를 부여 하고 순위로 오름차순으로 정렬하여 출력 하시오.

In [6]:
music_genre['순위'] = music_genre['Rating'].rank(method='first',ascending=False)
music_genre.sort_values(by='순위')

,Album Title,Artist Name,Rating,melt_Genre,genre,순위
1172,웹툰 연놈 OST Part 1,케이시(Kassy),9.8,Genre,O.S.T,1.0
1173,웹툰 연놈 OST Part 1,케이시(Kassy),9.8,Genre,O.S.T,2.0
1174,웹툰 연놈 OST Part 1,케이시(Kassy),9.8,Genre,O.S.T,3.0
2743,웹툰 연놈 OST Part 1,케이시(Kassy),9.8,Genre_new,발라드,4.0
2744,웹툰 연놈 OST Part 1,케이시(Kassy),9.8,Genre_new,발라드,5.0
...,...,...,...,...,...,...
3073,[Oct] Diary,피아노을(Piano:el),0.0,Genre_new,발라드,3138.0
3074,[Oct] Diary,피아노을(Piano:el),0.0,Genre_new,댄스,3139.0
3075,[Oct] Diary,피아노을(Piano:el),0.0,Genre_new,발라드,3140.0
3122,우리 지금 보다 영원 (Always with You),Dr. Slam 박정서,0.0,Genre_new,랩/힙합,3141.0
3123,우리 지금 보다 영원 (Always with You),Dr. Slam 박정서,0.0,Genre_new,랩/힙합,3142.0